const router = require('express').Router();
const { protect, authorize } = require('../middleware/auth');
const ctrl = require('../controllers/superadmin.controller');

router.use(protect, authorize('SuperAdmin'));
router.get('/stats', ctrl.getGlobalStats);
router.get('/stores', ctrl.getStores);
router.post('/stores', ctrl.createStore);
router.put('/stores/:id/approve', ctrl.approveStore);
router.put('/stores/:id/toggle', ctrl.toggleStore);
router.put('/stores/:id/suspend', ctrl.suspendStore);
router.put('/stores/:id/reactivate', ctrl.reactivateStore);
router.put('/stores/:id/plan', ctrl.updatePlan);
router.put('/stores/:id/catalog', ctrl.setStoreCatalog);
router.put('/stores/:id/admin-password', ctrl.resetStoreAdminPassword);
router.get('/stores/:id/controlled-module', ctrl.getControlledModule);
router.put('/stores/:id/controlled-module', ctrl.updateControlledModule);
router.put('/stores/:id/controlled-module/users', ctrl.setControlledModuleUsers);
router.get('/stores/:id/controlled-module/logs', ctrl.getControlledModuleLogs);
router.delete('/stores/:id', ctrl.deleteStore);
router.post('/medicines/bulk-master', ctrl.bulkMasterMedicines);
router.get('/medicines/master/stats', ctrl.getMasterStats);
router.get('/medicine-suggestions', ctrl.listMedicineSuggestions);
router.get('/medicine-suggestions/pending-count', ctrl.getMedicineSuggestionsPendingCount);
router.put('/medicine-suggestions/:id/approve', ctrl.approveMedicineSuggestion);
router.put('/medicine-suggestions/:id/reject', ctrl.rejectMedicineSuggestion);
router.get('/users', ctrl.getUsers);
router.put('/users/:id', ctrl.updateUser);

module.exports = router;
