// Complete World Medicines Database Generator
// Covers: Tablets, Capsules, Syrups, Injections, Drops, Creams, Inhalers, Suppositories, Patches, Gels, Sprays, Sachets, Powders etc.

const worldMedicines = [
  // ══════ PAINKILLERS / NSAIDS ══════
  {g:'Paracetamol',b:['Panadol','Tylenol','Calpol','Adol','Pyrigesic','Provas','Disprol','Fevadol','Emidol','Tempra'],c:'Tablet',s:['500mg','650mg','1000mg'],sc:'OTC',th:'Analgesic',df:'Oral'},
  {g:'Paracetamol',b:['Calpol','Panadol','Tylenol','Tempra','Adol'],c:'Syrup',s:['120mg/5ml','250mg/5ml'],sc:'OTC',th:'Analgesic',df:'Oral'},
  {g:'Paracetamol',b:['Perfalgan','Paracetamol IV'],c:'Injection',s:['1g/100ml'],sc:'Schedule-H',th:'Analgesic',df:'Injectable'},
  {g:'Paracetamol',b:['Calpol','Panadol'],c:'Drops',s:['100mg/ml'],sc:'OTC',th:'Analgesic',df:'Oral'},
  {g:'Paracetamol',b:['Panadol','Efferalgan'],c:'Suppository',s:['125mg','250mg','500mg'],sc:'OTC',th:'Analgesic',df:'Rectal'},
  {g:'Ibuprofen',b:['Brufen','Advil','Nurofen','Ibucap','Ibugesic','Motrin'],c:'Tablet',s:['200mg','400mg','600mg','800mg'],sc:'OTC',th:'NSAID',df:'Oral'},
  {g:'Ibuprofen',b:['Brufen','Nurofen','Caldolor'],c:'Syrup',s:['100mg/5ml','200mg/5ml'],sc:'OTC',th:'NSAID',df:'Oral'},
  {g:'Ibuprofen',b:['Nurofen','Ibugel'],c:'Gel',s:['5%','10%'],sc:'OTC',th:'NSAID',df:'Topical'},
  {g:'Diclofenac Sodium',b:['Voltaren','Diclofen','Voren','Jonac','Defnac','Cataflam'],c:'Tablet',s:['25mg','50mg','75mg','100mg'],sc:'Schedule-H',th:'NSAID',df:'Oral'},
  {g:'Diclofenac',b:['Voltaren','Diclofen'],c:'Injection',s:['75mg/3ml'],sc:'Schedule-H',th:'NSAID',df:'Injectable'},
  {g:'Diclofenac',b:['Voltaren','Voveran'],c:'Gel',s:['1%','2%'],sc:'OTC',th:'NSAID',df:'Topical'},
  {g:'Diclofenac',b:['Voltaren'],c:'Drops',s:['0.1%'],sc:'Schedule-H',th:'NSAID',df:'Ophthalmic'},
  {g:'Diclofenac',b:['Voltaren'],c:'Suppository',s:['12.5mg','25mg','50mg','100mg'],sc:'Schedule-H',th:'NSAID',df:'Rectal'},
  {g:'Naproxen',b:['Naprosyn','Proxen','Synflex','Aleve','Naprogesic'],c:'Tablet',s:['250mg','375mg','500mg'],sc:'Schedule-H',th:'NSAID',df:'Oral'},
  {g:'Aspirin',b:['Disprin','Ecotrin','Loprin','Cartia','Bayer Aspirin','Rivo'],c:'Tablet',s:['75mg','100mg','150mg','300mg','500mg'],sc:'OTC',th:'Analgesic/Antiplatelet',df:'Oral'},
  {g:'Mefenamic Acid',b:['Ponstan','Meftal','Mefac','Ponstan Forte'],c:'Capsule',s:['250mg','500mg'],sc:'Schedule-H',th:'NSAID',df:'Oral'},
  {g:'Mefenamic Acid',b:['Ponstan','Meftal'],c:'Syrup',s:['50mg/5ml'],sc:'Schedule-H',th:'NSAID',df:'Oral'},
  {g:'Tramadol',b:['Tramal','Contramal','Ultram','Tramadol'],c:'Capsule',s:['50mg','100mg'],sc:'Schedule-H1',th:'Opioid Analgesic',df:'Oral'},
  {g:'Tramadol',b:['Tramal'],c:'Injection',s:['50mg/ml','100mg/2ml'],sc:'Schedule-H1',th:'Opioid Analgesic',df:'Injectable'},
  {g:'Celecoxib',b:['Celebrex','Celbexx','Revibra'],c:'Capsule',s:['100mg','200mg'],sc:'Schedule-H',th:'COX-2 Inhibitor',df:'Oral'},
  {g:'Piroxicam',b:['Feldene','Pirox','Brexin'],c:'Capsule',s:['10mg','20mg'],sc:'Schedule-H',th:'NSAID',df:'Oral'},
  {g:'Piroxicam',b:['Feldene'],c:'Gel',s:['0.5%'],sc:'OTC',th:'NSAID',df:'Topical'},
  {g:'Ketorolac',b:['Toradol','Ketanov'],c:'Tablet',s:['10mg'],sc:'Schedule-H',th:'NSAID',df:'Oral'},
  {g:'Ketorolac',b:['Toradol'],c:'Injection',s:['30mg/ml'],sc:'Schedule-H',th:'NSAID',df:'Injectable'},
  {g:'Morphine',b:['MST Continus','Morphine Sulfate'],c:'Tablet',s:['10mg','30mg','60mg'],sc:'Schedule-X',th:'Opioid',df:'Oral'},
  {g:'Morphine',b:['Morphine'],c:'Injection',s:['10mg/ml','15mg/ml'],sc:'Schedule-X',th:'Opioid',df:'Injectable'},
  {g:'Codeine+Paracetamol',b:['Cocodamol','Panadol Ultra','Solpadeine'],c:'Tablet',s:['8/500mg','15/500mg','30/500mg'],sc:'Schedule-H1',th:'Opioid Analgesic',df:'Oral'},
  // ══════ ANTIBIOTICS ══════
  {g:'Amoxicillin',b:['Amoxil','Moxilin','Ospamox','Novamox','Polymox','Trimox'],c:'Capsule',s:['250mg','500mg'],sc:'Schedule-H',th:'Penicillin',df:'Oral'},
  {g:'Amoxicillin',b:['Amoxil','Moxilin','Ospamox'],c:'Syrup',s:['125mg/5ml','250mg/5ml'],sc:'Schedule-H',th:'Penicillin',df:'Oral'},
  {g:'Amoxicillin',b:['Amoxil'],c:'Drops',s:['100mg/ml'],sc:'Schedule-H',th:'Penicillin',df:'Oral'},
  {g:'Amoxicillin+Clavulanate',b:['Augmentin','Clavoxin','Enhancin','Novamox-CV'],c:'Tablet',s:['375mg','625mg','1g'],sc:'Schedule-H',th:'Penicillin+Inhibitor',df:'Oral'},
  {g:'Amoxicillin+Clavulanate',b:['Augmentin','Clavoxin'],c:'Syrup',s:['228mg/5ml','457mg/5ml'],sc:'Schedule-H',th:'Penicillin+Inhibitor',df:'Oral'},
  {g:'Azithromycin',b:['Zithromax','Aztrin','Azomax','Zetro','Azee','Zmax'],c:'Tablet',s:['250mg','500mg'],sc:'Schedule-H',th:'Macrolide',df:'Oral'},
  {g:'Azithromycin',b:['Zithromax','Aztrin'],c:'Syrup',s:['200mg/5ml'],sc:'Schedule-H',th:'Macrolide',df:'Oral'},
  {g:'Ciprofloxacin',b:['Cipro','Ciproxin','Ciplox','Novidat','Cifran'],c:'Tablet',s:['250mg','500mg','750mg'],sc:'Schedule-H',th:'Fluoroquinolone',df:'Oral'},
  {g:'Ciprofloxacin',b:['Cipro','Ciproxin'],c:'Injection',s:['200mg/100ml','400mg/200ml'],sc:'Schedule-H',th:'Fluoroquinolone',df:'Injectable'},
  {g:'Ciprofloxacin',b:['Ciloxan','Ciplox'],c:'Drops',s:['0.3%'],sc:'Schedule-H',th:'Fluoroquinolone',df:'Ophthalmic'},
  {g:'Levofloxacin',b:['Levaquin','Tavanic','Loxof','Cravit'],c:'Tablet',s:['250mg','500mg','750mg'],sc:'Schedule-H',th:'Fluoroquinolone',df:'Oral'},
  {g:'Moxifloxacin',b:['Avelox','Moxicip','Vigamox'],c:'Tablet',s:['400mg'],sc:'Schedule-H',th:'Fluoroquinolone',df:'Oral'},
  {g:'Moxifloxacin',b:['Vigamox','Moxicip'],c:'Drops',s:['0.5%'],sc:'Schedule-H',th:'Fluoroquinolone',df:'Ophthalmic'},
  {g:'Cefixime',b:['Suprax','Cefix','Fixef','Cephime'],c:'Tablet',s:['200mg','400mg'],sc:'Schedule-H',th:'Cephalosporin-3',df:'Oral'},
  {g:'Cefixime',b:['Suprax','Cefix'],c:'Syrup',s:['100mg/5ml'],sc:'Schedule-H',th:'Cephalosporin-3',df:'Oral'},
  {g:'Ceftriaxone',b:['Rocephin','Ceftron','Injicef','Triaxone'],c:'Injection',s:['250mg','500mg','1g','2g'],sc:'Schedule-H',th:'Cephalosporin-3',df:'Injectable'},
  {g:'Cefuroxime',b:['Zinnat','Ceftin','Zinacef'],c:'Tablet',s:['250mg','500mg'],sc:'Schedule-H',th:'Cephalosporin-2',df:'Oral'},
  {g:'Cephalexin',b:['Keflex','Cefalin','Sporidex'],c:'Capsule',s:['250mg','500mg'],sc:'Schedule-H',th:'Cephalosporin-1',df:'Oral'},
  {g:'Cephalexin',b:['Keflex','Cefalin'],c:'Syrup',s:['125mg/5ml','250mg/5ml'],sc:'Schedule-H',th:'Cephalosporin-1',df:'Oral'},
  {g:'Metronidazole',b:['Flagyl','Metro','Metrozol','Arilin'],c:'Tablet',s:['200mg','400mg','500mg'],sc:'Schedule-H',th:'Nitroimidazole',df:'Oral'},
  {g:'Metronidazole',b:['Flagyl'],c:'Syrup',s:['200mg/5ml'],sc:'Schedule-H',th:'Nitroimidazole',df:'Oral'},
  {g:'Metronidazole',b:['Flagyl','Metrogyl'],c:'Injection',s:['500mg/100ml'],sc:'Schedule-H',th:'Nitroimidazole',df:'Injectable'},
  {g:'Metronidazole',b:['Flagyl','Metrogyl'],c:'Gel',s:['0.75%','1%'],sc:'Schedule-H',th:'Nitroimidazole',df:'Topical'},
  {g:'Doxycycline',b:['Vibramycin','Doxylin','Monodox'],c:'Capsule',s:['50mg','100mg'],sc:'Schedule-H',th:'Tetracycline',df:'Oral'},
  {g:'Clarithromycin',b:['Klacid','Klaricid','Claribid','Biaxin'],c:'Tablet',s:['250mg','500mg'],sc:'Schedule-H',th:'Macrolide',df:'Oral'},
  {g:'Clindamycin',b:['Dalacin','Clindac','Cleocin'],c:'Capsule',s:['150mg','300mg'],sc:'Schedule-H',th:'Lincosamide',df:'Oral'},
  {g:'Clindamycin',b:['Dalacin-T','Clindac-A'],c:'Gel',s:['1%'],sc:'Schedule-H',th:'Lincosamide',df:'Topical'},
  {g:'Erythromycin',b:['Erythrocin','Eryc','Erytop'],c:'Tablet',s:['250mg','500mg'],sc:'Schedule-H',th:'Macrolide',df:'Oral'},
  {g:'Nitrofurantoin',b:['Macrobid','Furadantin'],c:'Capsule',s:['50mg','100mg'],sc:'Schedule-H',th:'Nitrofuran',df:'Oral'},
  {g:'Cotrimoxazole',b:['Septran','Bactrim','Septra'],c:'Tablet',s:['480mg','960mg'],sc:'Schedule-H',th:'Sulfonamide',df:'Oral'},
  {g:'Cotrimoxazole',b:['Septran','Bactrim'],c:'Syrup',s:['240mg/5ml'],sc:'Schedule-H',th:'Sulfonamide',df:'Oral'},
  {g:'Vancomycin',b:['Vancocin','Vancomycin'],c:'Injection',s:['500mg','1g'],sc:'Schedule-H',th:'Glycopeptide',df:'Injectable'},
  {g:'Meropenem',b:['Meronem','Merocrit'],c:'Injection',s:['500mg','1g'],sc:'Schedule-H',th:'Carbapenem',df:'Injectable'},
  {g:'Piperacillin+Tazobactam',b:['Zosyn','Tazocin'],c:'Injection',s:['4.5g'],sc:'Schedule-H',th:'Penicillin+Inhibitor',df:'Injectable'},
  // ══════ GASTRO / GI ══════
  {g:'Omeprazole',b:['Omez','Losec','Risek','Omepral','Gastrozol','Prilosec'],c:'Capsule',s:['10mg','20mg','40mg'],sc:'OTC',th:'PPI',df:'Oral'},
  {g:'Omeprazole',b:['Losec'],c:'Injection',s:['40mg'],sc:'Schedule-H',th:'PPI',df:'Injectable'},
  {g:'Esomeprazole',b:['Nexium','Esomax','Esogard'],c:'Tablet',s:['20mg','40mg'],sc:'Schedule-H',th:'PPI',df:'Oral'},
  {g:'Pantoprazole',b:['Protonix','Pantop','Pantozol','Pantocid'],c:'Tablet',s:['20mg','40mg'],sc:'Schedule-H',th:'PPI',df:'Oral'},
  {g:'Pantoprazole',b:['Protonix'],c:'Injection',s:['40mg'],sc:'Schedule-H',th:'PPI',df:'Injectable'},
  {g:'Rabeprazole',b:['Pariet','Razo','Aciphex'],c:'Tablet',s:['10mg','20mg'],sc:'Schedule-H',th:'PPI',df:'Oral'},
  {g:'Lansoprazole',b:['Prevacid','Lanzol'],c:'Capsule',s:['15mg','30mg'],sc:'Schedule-H',th:'PPI',df:'Oral'},
  {g:'Ranitidine',b:['Zantac','Rani','Aciloc'],c:'Tablet',s:['150mg','300mg'],sc:'OTC',th:'H2 Blocker',df:'Oral'},
  {g:'Famotidine',b:['Pepcid','Famocid'],c:'Tablet',s:['20mg','40mg'],sc:'OTC',th:'H2 Blocker',df:'Oral'},
  {g:'Domperidone',b:['Motilium','Domstal','Vomistop','Peridone'],c:'Tablet',s:['10mg'],sc:'Schedule-H',th:'Prokinetic',df:'Oral'},
  {g:'Domperidone',b:['Motilium'],c:'Syrup',s:['5mg/5ml'],sc:'Schedule-H',th:'Prokinetic',df:'Oral'},
  {g:'Metoclopramide',b:['Maxolon','Perinorm','Reglan'],c:'Tablet',s:['10mg'],sc:'Schedule-H',th:'Prokinetic',df:'Oral'},
  {g:'Metoclopramide',b:['Maxolon'],c:'Injection',s:['10mg/2ml'],sc:'Schedule-H',th:'Prokinetic',df:'Injectable'},
  {g:'Ondansetron',b:['Zofran','Emeset','Vomikind'],c:'Tablet',s:['4mg','8mg'],sc:'Schedule-H',th:'5-HT3 Antagonist',df:'Oral'},
  {g:'Ondansetron',b:['Zofran'],c:'Injection',s:['4mg/2ml','8mg/4ml'],sc:'Schedule-H',th:'5-HT3 Antagonist',df:'Injectable'},
  {g:'Loperamide',b:['Imodium','Lopamide','Eldoper'],c:'Capsule',s:['2mg'],sc:'OTC',th:'Antidiarrheal',df:'Oral'},
  {g:'ORS',b:['Pedialyte','Hydrite','Enerlyte','Electrosol'],c:'Sachet',s:['21g'],sc:'OTC',th:'Rehydration',df:'Oral'},
  {g:'Lactulose',b:['Duphalac','Laxose','Lactifiber'],c:'Syrup',s:['10g/15ml'],sc:'OTC',th:'Osmotic Laxative',df:'Oral'},
  {g:'Bisacodyl',b:['Dulcolax','Bisacodyl'],c:'Tablet',s:['5mg','10mg'],sc:'OTC',th:'Stimulant Laxative',df:'Oral'},
  {g:'Bisacodyl',b:['Dulcolax'],c:'Suppository',s:['5mg','10mg'],sc:'OTC',th:'Stimulant Laxative',df:'Rectal'},
  {g:'Sucralfate',b:['Sucral','Carafate'],c:'Tablet',s:['1g'],sc:'Schedule-H',th:'Mucosal Protectant',df:'Oral'},
  {g:'Sucralfate',b:['Sucral'],c:'Syrup',s:['1g/5ml'],sc:'Schedule-H',th:'Mucosal Protectant',df:'Oral'},
  {g:'Antacid (Al+Mg)',b:['Gaviscon','Maalox','Mucaine','Gelusil','Mylanta'],c:'Syrup',s:['170ml','240ml'],sc:'OTC',th:'Antacid',df:'Oral'},
  {g:'Antacid (Al+Mg)',b:['Gaviscon','Gelusil','Digene'],c:'Tablet',s:['400mg'],sc:'OTC',th:'Antacid',df:'Oral'},
  // ══════ CARDIAC / BP / CHOLESTEROL ══════
  {g:'Amlodipine',b:['Norvasc','Amlo','Amlong','Amlopress','Caduet'],c:'Tablet',s:['2.5mg','5mg','10mg'],sc:'Schedule-H',th:'CCB',df:'Oral'},
  {g:'Atenolol',b:['Tenormin','Aten','Betacard'],c:'Tablet',s:['25mg','50mg','100mg'],sc:'Schedule-H',th:'Beta-Blocker',df:'Oral'},
  {g:'Metoprolol',b:['Lopressor','Betaloc','Seloken','Toprol'],c:'Tablet',s:['25mg','50mg','100mg','200mg'],sc:'Schedule-H',th:'Beta-Blocker',df:'Oral'},
  {g:'Bisoprolol',b:['Concor','Bisoprolol'],c:'Tablet',s:['2.5mg','5mg','10mg'],sc:'Schedule-H',th:'Beta-Blocker',df:'Oral'},
  {g:'Propranolol',b:['Inderal','Propranolol'],c:'Tablet',s:['10mg','20mg','40mg','80mg'],sc:'Schedule-H',th:'Beta-Blocker',df:'Oral'},
  {g:'Losartan',b:['Cozaar','Losacar','Losar','Repace'],c:'Tablet',s:['25mg','50mg','100mg'],sc:'Schedule-H',th:'ARB',df:'Oral'},
  {g:'Valsartan',b:['Diovan','Valzaar'],c:'Tablet',s:['40mg','80mg','160mg','320mg'],sc:'Schedule-H',th:'ARB',df:'Oral'},
  {g:'Telmisartan',b:['Micardis','Telma','Telvas'],c:'Tablet',s:['20mg','40mg','80mg'],sc:'Schedule-H',th:'ARB',df:'Oral'},
  {g:'Enalapril',b:['Vasotec','Renitec','Enapril'],c:'Tablet',s:['2.5mg','5mg','10mg','20mg'],sc:'Schedule-H',th:'ACE Inhibitor',df:'Oral'},
  {g:'Ramipril',b:['Altace','Tritace','Cardace'],c:'Capsule',s:['1.25mg','2.5mg','5mg','10mg'],sc:'Schedule-H',th:'ACE Inhibitor',df:'Oral'},
  {g:'Lisinopril',b:['Zestril','Prinivil'],c:'Tablet',s:['2.5mg','5mg','10mg','20mg'],sc:'Schedule-H',th:'ACE Inhibitor',df:'Oral'},
  {g:'Hydrochlorothiazide',b:['Esidrex','HCT','Aquazide'],c:'Tablet',s:['12.5mg','25mg','50mg'],sc:'Schedule-H',th:'Thiazide Diuretic',df:'Oral'},
  {g:'Furosemide',b:['Lasix','Frusenex'],c:'Tablet',s:['20mg','40mg','80mg'],sc:'Schedule-H',th:'Loop Diuretic',df:'Oral'},
  {g:'Furosemide',b:['Lasix'],c:'Injection',s:['20mg/2ml'],sc:'Schedule-H',th:'Loop Diuretic',df:'Injectable'},
  {g:'Spironolactone',b:['Aldactone','Spiromide'],c:'Tablet',s:['25mg','50mg','100mg'],sc:'Schedule-H',th:'K-sparing Diuretic',df:'Oral'},
  {g:'Clopidogrel',b:['Plavix','Clopilet','Plagril'],c:'Tablet',s:['75mg','150mg'],sc:'Schedule-H',th:'Antiplatelet',df:'Oral'},
  {g:'Warfarin',b:['Coumadin','Warf','Marevan'],c:'Tablet',s:['1mg','2mg','3mg','5mg'],sc:'Schedule-H',th:'Anticoagulant',df:'Oral'},
  {g:'Enoxaparin',b:['Clexane','Lovenox'],c:'Injection',s:['20mg','40mg','60mg','80mg'],sc:'Schedule-H',th:'LMWH',df:'Injectable'},
  {g:'Heparin',b:['Heparin'],c:'Injection',s:['5000IU/ml'],sc:'Schedule-H',th:'Anticoagulant',df:'Injectable'},
  {g:'Atorvastatin',b:['Lipitor','Atorva','Storvas'],c:'Tablet',s:['10mg','20mg','40mg','80mg'],sc:'Schedule-H',th:'Statin',df:'Oral'},
  {g:'Rosuvastatin',b:['Crestor','Rosuvas','Rozavel'],c:'Tablet',s:['5mg','10mg','20mg','40mg'],sc:'Schedule-H',th:'Statin',df:'Oral'},
  {g:'Simvastatin',b:['Zocor','Simcard'],c:'Tablet',s:['10mg','20mg','40mg'],sc:'Schedule-H',th:'Statin',df:'Oral'},
  {g:'Digoxin',b:['Lanoxin','Digox'],c:'Tablet',s:['0.0625mg','0.125mg','0.25mg'],sc:'Schedule-H',th:'Cardiac Glycoside',df:'Oral'},
  {g:'Nitroglycerin',b:['GTN','Nitrostat','Nitrolingual'],c:'Tablet',s:['0.3mg','0.4mg','0.6mg'],sc:'Schedule-H',th:'Nitrate',df:'Sublingual'},
  {g:'Nitroglycerin',b:['Nitroderm'],c:'Patch',s:['5mg','10mg','25mg'],sc:'Schedule-H',th:'Nitrate',df:'Transdermal'},
  {g:'Isosorbide Mononitrate',b:['Imdur','Monoket'],c:'Tablet',s:['10mg','20mg','30mg','60mg'],sc:'Schedule-H',th:'Nitrate',df:'Oral'},
  // ══════ DIABETES ══════
  {g:'Metformin',b:['Glucophage','Glycomet','Glumet','Obimet','Fortamet'],c:'Tablet',s:['250mg','500mg','850mg','1000mg'],sc:'Schedule-H',th:'Biguanide',df:'Oral'},
  {g:'Glimepiride',b:['Amaryl','Glimpid','Glimstar'],c:'Tablet',s:['1mg','2mg','3mg','4mg'],sc:'Schedule-H',th:'Sulfonylurea',df:'Oral'},
  {g:'Gliclazide',b:['Diamicron','Glizid'],c:'Tablet',s:['30mg','40mg','60mg','80mg'],sc:'Schedule-H',th:'Sulfonylurea',df:'Oral'},
  {g:'Glibenclamide',b:['Daonil','Euglucon'],c:'Tablet',s:['2.5mg','5mg'],sc:'Schedule-H',th:'Sulfonylurea',df:'Oral'},
  {g:'Sitagliptin',b:['Januvia','Sitaglu','Zita'],c:'Tablet',s:['25mg','50mg','100mg'],sc:'Schedule-H',th:'DPP-4 Inhibitor',df:'Oral'},
  {g:'Vildagliptin',b:['Galvus','Zomelis'],c:'Tablet',s:['50mg'],sc:'Schedule-H',th:'DPP-4 Inhibitor',df:'Oral'},
  {g:'Empagliflozin',b:['Jardiance'],c:'Tablet',s:['10mg','25mg'],sc:'Schedule-H',th:'SGLT2 Inhibitor',df:'Oral'},
  {g:'Dapagliflozin',b:['Forxiga','Farxiga'],c:'Tablet',s:['5mg','10mg'],sc:'Schedule-H',th:'SGLT2 Inhibitor',df:'Oral'},
  {g:'Pioglitazone',b:['Actos','Pioglar'],c:'Tablet',s:['15mg','30mg','45mg'],sc:'Schedule-H',th:'Thiazolidinedione',df:'Oral'},
  {g:'Insulin Glargine',b:['Lantus','Basalog','Glaritus','Toujeo'],c:'Injection',s:['100IU/ml','300IU/ml'],sc:'Schedule-H',th:'Long-acting Insulin',df:'Injectable'},
  {g:'Insulin Regular',b:['Actrapid','Humulin R','Insuman'],c:'Injection',s:['100IU/ml'],sc:'Schedule-H',th:'Short-acting Insulin',df:'Injectable'},
  {g:'Insulin Aspart',b:['NovoRapid','Fiasp'],c:'Injection',s:['100IU/ml'],sc:'Schedule-H',th:'Rapid-acting Insulin',df:'Injectable'},
  {g:'Insulin Mixtard',b:['Mixtard 30/70','Novomix','Humalog Mix'],c:'Injection',s:['100IU/ml'],sc:'Schedule-H',th:'Premixed Insulin',df:'Injectable'},
  // ══════ RESPIRATORY ══════
  {g:'Salbutamol',b:['Ventolin','Asthalin','ProAir'],c:'Inhaler',s:['100mcg/puff'],sc:'Schedule-H',th:'SABA',df:'Inhalation'},
  {g:'Salbutamol',b:['Ventolin','Asthalin'],c:'Syrup',s:['2mg/5ml'],sc:'Schedule-H',th:'SABA',df:'Oral'},
  {g:'Salbutamol',b:['Ventolin'],c:'Tablet',s:['2mg','4mg'],sc:'Schedule-H',th:'SABA',df:'Oral'},
  {g:'Salbutamol',b:['Ventolin'],c:'Solution',s:['5mg/ml'],sc:'Schedule-H',th:'SABA',df:'Inhalation'},
  {g:'Ipratropium Bromide',b:['Atrovent','Ipravent'],c:'Inhaler',s:['20mcg/puff'],sc:'Schedule-H',th:'Anticholinergic',df:'Inhalation'},
  {g:'Budesonide',b:['Pulmicort','Budecort'],c:'Inhaler',s:['100mcg','200mcg','400mcg'],sc:'Schedule-H',th:'ICS',df:'Inhalation'},
  {g:'Budesonide+Formoterol',b:['Symbicort','Foracort'],c:'Inhaler',s:['100/6mcg','200/6mcg','400/12mcg'],sc:'Schedule-H',th:'ICS+LABA',df:'Inhalation'},
  {g:'Fluticasone+Salmeterol',b:['Seretide','Advair','Salmeter'],c:'Inhaler',s:['125/25mcg','250/25mcg','500/50mcg'],sc:'Schedule-H',th:'ICS+LABA',df:'Inhalation'},
  {g:'Montelukast',b:['Singulair','Montair','Montek'],c:'Tablet',s:['4mg','5mg','10mg'],sc:'Schedule-H',th:'LTRA',df:'Oral'},
  {g:'Montelukast',b:['Singulair','Montair'],c:'Sachet',s:['4mg'],sc:'Schedule-H',th:'LTRA',df:'Oral'},
  {g:'Theophylline',b:['Theo-24','Uniphyllin'],c:'Tablet',s:['100mg','200mg','300mg'],sc:'Schedule-H',th:'Methylxanthine',df:'Oral'},
  {g:'Dextromethorphan+Guaifenesin',b:['Robitussin','Corex-DX','Benylin'],c:'Syrup',s:['100ml','120ml'],sc:'OTC',th:'Cough Suppressant',df:'Oral'},
  {g:'Bromhexine',b:['Bisolvon','Bromhexine'],c:'Syrup',s:['4mg/5ml','8mg/5ml'],sc:'OTC',th:'Mucolytic',df:'Oral'},
  {g:'Bromhexine',b:['Bisolvon'],c:'Tablet',s:['8mg'],sc:'OTC',th:'Mucolytic',df:'Oral'},
  {g:'Ambroxol',b:['Mucosolvan','Ambrodil','Ambroxol'],c:'Syrup',s:['15mg/5ml','30mg/5ml'],sc:'OTC',th:'Mucolytic',df:'Oral'},
  {g:'N-Acetylcysteine',b:['Mucomyst','Fluimucil','ACC'],c:'Sachet',s:['200mg','600mg'],sc:'OTC',th:'Mucolytic',df:'Oral'},
  {g:'Beclomethasone',b:['Beconase','Beclate'],c:'Spray',s:['50mcg','100mcg','250mcg'],sc:'Schedule-H',th:'Nasal Steroid',df:'Nasal'},
  {g:'Fluticasone Nasal',b:['Flonase','Flixonase','Avamys'],c:'Spray',s:['27.5mcg','50mcg'],sc:'OTC',th:'Nasal Steroid',df:'Nasal'},
  {g:'Oxymetazoline',b:['Afrin','Nasivion','Otrivin-O'],c:'Drops',s:['0.025%','0.05%'],sc:'OTC',th:'Nasal Decongestant',df:'Nasal'},
  {g:'Xylometazoline',b:['Otrivin','Xylomist'],c:'Drops',s:['0.05%','0.1%'],sc:'OTC',th:'Nasal Decongestant',df:'Nasal'},
  // ══════ ANTIHISTAMINES / ALLERGY ══════
  {g:'Cetirizine',b:['Zyrtec','Cetriz','Alerid','Incid'],c:'Tablet',s:['5mg','10mg'],sc:'OTC',th:'Antihistamine-2G',df:'Oral'},
  {g:'Cetirizine',b:['Zyrtec','Cetriz'],c:'Syrup',s:['5mg/5ml'],sc:'OTC',th:'Antihistamine-2G',df:'Oral'},
  {g:'Cetirizine',b:['Zyrtec'],c:'Drops',s:['10mg/ml'],sc:'OTC',th:'Antihistamine-2G',df:'Oral'},
  {g:'Loratadine',b:['Claritin','Lorfast','Alavert'],c:'Tablet',s:['10mg'],sc:'OTC',th:'Antihistamine-2G',df:'Oral'},
  {g:'Loratadine',b:['Claritin'],c:'Syrup',s:['5mg/5ml'],sc:'OTC',th:'Antihistamine-2G',df:'Oral'},
  {g:'Fexofenadine',b:['Allegra','Fexo','Telfast'],c:'Tablet',s:['60mg','120mg','180mg'],sc:'OTC',th:'Antihistamine-2G',df:'Oral'},
  {g:'Levocetirizine',b:['Xyzal','Levocet'],c:'Tablet',s:['5mg'],sc:'OTC',th:'Antihistamine-2G',df:'Oral'},
  {g:'Desloratadine',b:['Aerius','Deslor'],c:'Tablet',s:['5mg'],sc:'OTC',th:'Antihistamine-3G',df:'Oral'},
  {g:'Chlorpheniramine',b:['Piriton','Avil','CTM'],c:'Tablet',s:['4mg'],sc:'OTC',th:'Antihistamine-1G',df:'Oral'},
  {g:'Chlorpheniramine',b:['Piriton'],c:'Syrup',s:['2mg/5ml'],sc:'OTC',th:'Antihistamine-1G',df:'Oral'},
  {g:'Promethazine',b:['Phenergan','Avomine'],c:'Tablet',s:['10mg','25mg'],sc:'Schedule-H',th:'Antihistamine-1G',df:'Oral'},
  {g:'Promethazine',b:['Phenergan'],c:'Syrup',s:['5mg/5ml'],sc:'Schedule-H',th:'Antihistamine-1G',df:'Oral'},
  {g:'Hydroxyzine',b:['Atarax','Vistaril'],c:'Tablet',s:['10mg','25mg'],sc:'Schedule-H',th:'Antihistamine-1G',df:'Oral'},
  // ══════ SKIN / TOPICAL ══════
  {g:'Clotrimazole',b:['Canesten','Candid','Clotrim'],c:'Cream/Ointment',s:['1%'],sc:'OTC',th:'Antifungal',df:'Topical'},
  {g:'Clotrimazole',b:['Canesten'],c:'Drops',s:['1%'],sc:'OTC',th:'Antifungal',df:'Otic'},
  {g:'Miconazole',b:['Daktarin','Micogel'],c:'Cream/Ointment',s:['2%'],sc:'OTC',th:'Antifungal',df:'Topical'},
  {g:'Miconazole',b:['Daktarin'],c:'Gel',s:['2%'],sc:'OTC',th:'Antifungal',df:'Oral'},
  {g:'Ketoconazole',b:['Nizoral','Ketomac'],c:'Cream/Ointment',s:['2%'],sc:'OTC',th:'Antifungal',df:'Topical'},
  {g:'Ketoconazole',b:['Nizoral','Ketomac'],c:'Syrup',s:['2%'],sc:'OTC',th:'Antifungal Shampoo',df:'Topical'},
  {g:'Terbinafine',b:['Lamisil','Terbicip'],c:'Cream/Ointment',s:['1%'],sc:'OTC',th:'Antifungal',df:'Topical'},
  {g:'Terbinafine',b:['Lamisil','Terbicip'],c:'Tablet',s:['250mg'],sc:'Schedule-H',th:'Antifungal',df:'Oral'},
  {g:'Betamethasone',b:['Betnovate','Betaderm','Diprosone'],c:'Cream/Ointment',s:['0.05%','0.1%'],sc:'Schedule-H',th:'Topical Steroid',df:'Topical'},
  {g:'Hydrocortisone',b:['Cortaid','Hydrocort'],c:'Cream/Ointment',s:['0.5%','1%','2.5%'],sc:'OTC',th:'Topical Steroid',df:'Topical'},
  {g:'Clobetasol',b:['Dermovate','Clobevate','Temovate'],c:'Cream/Ointment',s:['0.05%'],sc:'Schedule-H',th:'Topical Steroid',df:'Topical'},
  {g:'Mupirocin',b:['Bactroban','Mupiderm','T-Bact'],c:'Cream/Ointment',s:['2%'],sc:'Schedule-H',th:'Topical Antibiotic',df:'Topical'},
  {g:'Fusidic Acid',b:['Fucidin','Fusicip'],c:'Cream/Ointment',s:['2%'],sc:'Schedule-H',th:'Topical Antibiotic',df:'Topical'},
  {g:'Silver Sulfadiazine',b:['Silverex','Silvadene'],c:'Cream/Ointment',s:['1%'],sc:'Schedule-H',th:'Burn Cream',df:'Topical'},
  {g:'Calamine',b:['Calamine','Lacto Calamine'],c:'Lotion',s:['100ml','200ml'],sc:'OTC',th:'Soothing',df:'Topical'},
  {g:'Permethrin',b:['Elimite','Lyclear','Permitex'],c:'Cream/Ointment',s:['5%'],sc:'OTC',th:'Scabicide',df:'Topical'},
  {g:'Permethrin',b:['Lyclear'],c:'Lotion',s:['1%'],sc:'OTC',th:'Pediculicide',df:'Topical'},
  {g:'Benzoyl Peroxide',b:['Benzac','Brevoxyl','PanOxyl'],c:'Gel',s:['2.5%','5%','10%'],sc:'OTC',th:'Acne',df:'Topical'},
  {g:'Adapalene',b:['Differin','Adaferin'],c:'Gel',s:['0.1%','0.3%'],sc:'Schedule-H',th:'Retinoid',df:'Topical'},
  {g:'Tretinoin',b:['Retin-A','Retino-A'],c:'Cream/Ointment',s:['0.025%','0.05%','0.1%'],sc:'Schedule-H',th:'Retinoid',df:'Topical'},
  {g:'Isotretinoin',b:['Accutane','Roaccutane','Tretiva'],c:'Capsule',s:['10mg','20mg','40mg'],sc:'Schedule-H',th:'Systemic Retinoid',df:'Oral'},
  // ══════ EYE ══════
  {g:'Ciprofloxacin Eye',b:['Ciloxan','Ciplox Eye'],c:'Drops',s:['0.3%'],sc:'Schedule-H',th:'Ophthalmic Antibiotic',df:'Ophthalmic'},
  {g:'Tobramycin Eye',b:['Tobrex','Tobracin'],c:'Drops',s:['0.3%'],sc:'Schedule-H',th:'Ophthalmic Antibiotic',df:'Ophthalmic'},
  {g:'Chloramphenicol Eye',b:['Chloromycetin'],c:'Drops',s:['0.5%'],sc:'Schedule-H',th:'Ophthalmic Antibiotic',df:'Ophthalmic'},
  {g:'Artificial Tears',b:['Refresh','Tears Naturale','Systane','Genteal'],c:'Drops',s:['10ml','15ml'],sc:'OTC',th:'Eye Lubricant',df:'Ophthalmic'},
  {g:'Timolol Eye',b:['Timoptic','Iotim'],c:'Drops',s:['0.25%','0.5%'],sc:'Schedule-H',th:'Glaucoma',df:'Ophthalmic'},
  {g:'Latanoprost',b:['Xalatan','Latoprost'],c:'Drops',s:['0.005%'],sc:'Schedule-H',th:'Glaucoma',df:'Ophthalmic'},
  {g:'Prednisolone Eye',b:['Pred Forte','Prednisolone'],c:'Drops',s:['0.5%','1%'],sc:'Schedule-H',th:'Ophthalmic Steroid',df:'Ophthalmic'},
  {g:'Ofloxacin Eye',b:['Ocuflox','Oflox Eye'],c:'Drops',s:['0.3%'],sc:'Schedule-H',th:'Ophthalmic Antibiotic',df:'Ophthalmic'},
  // ══════ MENTAL HEALTH ══════
  {g:'Sertraline',b:['Zoloft','Serlift','Daxid'],c:'Tablet',s:['25mg','50mg','100mg'],sc:'Schedule-H',th:'SSRI',df:'Oral'},
  {g:'Escitalopram',b:['Lexapro','Cipralex','Nexito'],c:'Tablet',s:['5mg','10mg','20mg'],sc:'Schedule-H',th:'SSRI',df:'Oral'},
  {g:'Fluoxetine',b:['Prozac','Fludac'],c:'Capsule',s:['10mg','20mg','40mg'],sc:'Schedule-H',th:'SSRI',df:'Oral'},
  {g:'Paroxetine',b:['Paxil','Paxit','Paxidep'],c:'Tablet',s:['12.5mg','20mg','25mg'],sc:'Schedule-H',th:'SSRI',df:'Oral'},
  {g:'Venlafaxine',b:['Effexor','Veniz'],c:'Capsule',s:['37.5mg','75mg','150mg'],sc:'Schedule-H',th:'SNRI',df:'Oral'},
  {g:'Duloxetine',b:['Cymbalta','Duzela'],c:'Capsule',s:['20mg','30mg','60mg'],sc:'Schedule-H',th:'SNRI',df:'Oral'},
  {g:'Amitriptyline',b:['Elavil','Tryptomer'],c:'Tablet',s:['10mg','25mg','50mg','75mg'],sc:'Schedule-H',th:'TCA',df:'Oral'},
  {g:'Mirtazapine',b:['Remeron','Mirtaz'],c:'Tablet',s:['7.5mg','15mg','30mg','45mg'],sc:'Schedule-H',th:'NaSSA',df:'Oral'},
  {g:'Alprazolam',b:['Xanax','Restyl','Alprax'],c:'Tablet',s:['0.25mg','0.5mg','1mg'],sc:'Schedule-X',th:'Benzodiazepine',df:'Oral'},
  {g:'Diazepam',b:['Valium','Calmpose','Diazep'],c:'Tablet',s:['2mg','5mg','10mg'],sc:'Schedule-X',th:'Benzodiazepine',df:'Oral'},
  {g:'Diazepam',b:['Valium'],c:'Injection',s:['10mg/2ml'],sc:'Schedule-X',th:'Benzodiazepine',df:'Injectable'},
  {g:'Clonazepam',b:['Rivotril','Clonotril','Epitril'],c:'Tablet',s:['0.25mg','0.5mg','1mg','2mg'],sc:'Schedule-X',th:'Benzodiazepine',df:'Oral'},
  {g:'Lorazepam',b:['Ativan','Lorazep'],c:'Tablet',s:['0.5mg','1mg','2mg'],sc:'Schedule-X',th:'Benzodiazepine',df:'Oral'},
  {g:'Zolpidem',b:['Ambien','Stilnox','Zolfresh'],c:'Tablet',s:['5mg','10mg'],sc:'Schedule-X',th:'Z-drug Hypnotic',df:'Oral'},
  {g:'Olanzapine',b:['Zyprexa','Oleanz'],c:'Tablet',s:['2.5mg','5mg','10mg','15mg'],sc:'Schedule-H',th:'Atypical Antipsychotic',df:'Oral'},
  {g:'Risperidone',b:['Risperdal','Risnia','Sizodon'],c:'Tablet',s:['1mg','2mg','3mg','4mg'],sc:'Schedule-H',th:'Atypical Antipsychotic',df:'Oral'},
  {g:'Quetiapine',b:['Seroquel','Quel'],c:'Tablet',s:['25mg','50mg','100mg','200mg','300mg'],sc:'Schedule-H',th:'Atypical Antipsychotic',df:'Oral'},
  {g:'Lithium',b:['Eskalith','Lithobid','Licab'],c:'Tablet',s:['300mg','450mg'],sc:'Schedule-H',th:'Mood Stabilizer',df:'Oral'},
  {g:'Haloperidol',b:['Haldol','Serenace'],c:'Tablet',s:['0.5mg','1mg','2mg','5mg','10mg'],sc:'Schedule-H',th:'Typical Antipsychotic',df:'Oral'},
  {g:'Haloperidol',b:['Haldol'],c:'Injection',s:['5mg/ml'],sc:'Schedule-H',th:'Typical Antipsychotic',df:'Injectable'},
  // ══════ ANTI-EPILEPTICS ══════
  {g:'Gabapentin',b:['Neurontin','Gabapin'],c:'Capsule',s:['100mg','300mg','400mg','600mg','800mg'],sc:'Schedule-H',th:'Gabapentinoid',df:'Oral'},
  {g:'Pregabalin',b:['Lyrica','Pregalin'],c:'Capsule',s:['25mg','50mg','75mg','100mg','150mg','300mg'],sc:'Schedule-H1',th:'Gabapentinoid',df:'Oral'},
  {g:'Carbamazepine',b:['Tegretol','Carbatol','Mazetol'],c:'Tablet',s:['100mg','200mg','400mg'],sc:'Schedule-H',th:'Anticonvulsant',df:'Oral'},
  {g:'Valproic Acid',b:['Depakote','Epilim','Valparin'],c:'Tablet',s:['200mg','250mg','500mg'],sc:'Schedule-H',th:'Anticonvulsant',df:'Oral'},
  {g:'Valproic Acid',b:['Epilim'],c:'Syrup',s:['200mg/5ml'],sc:'Schedule-H',th:'Anticonvulsant',df:'Oral'},
  {g:'Levetiracetam',b:['Keppra','Levera'],c:'Tablet',s:['250mg','500mg','750mg','1000mg'],sc:'Schedule-H',th:'Anticonvulsant',df:'Oral'},
  {g:'Phenytoin',b:['Dilantin','Eptoin'],c:'Tablet',s:['50mg','100mg','300mg'],sc:'Schedule-H',th:'Anticonvulsant',df:'Oral'},
  {g:'Lamotrigine',b:['Lamictal','Lamitor'],c:'Tablet',s:['25mg','50mg','100mg','200mg'],sc:'Schedule-H',th:'Anticonvulsant',df:'Oral'},
  // ══════ THYROID ══════
  {g:'Levothyroxine',b:['Synthroid','Eltroxin','Thyronorm','Euthyrox'],c:'Tablet',s:['12.5mcg','25mcg','50mcg','75mcg','88mcg','100mcg','112mcg','125mcg','150mcg','175mcg','200mcg'],sc:'Schedule-H',th:'Thyroid Hormone',df:'Oral'},
  {g:'Methimazole',b:['Tapazole','Neomercazole'],c:'Tablet',s:['5mg','10mg','20mg'],sc:'Schedule-H',th:'Antithyroid',df:'Oral'},
  {g:'Propylthiouracil',b:['PTU'],c:'Tablet',s:['50mg','100mg'],sc:'Schedule-H',th:'Antithyroid',df:'Oral'},
  // ══════ STEROIDS / ANTI-INFLAMMATORY ══════
  {g:'Prednisolone',b:['Omnacortil','Wysolone','Prelone','Deltacortril'],c:'Tablet',s:['5mg','10mg','20mg','40mg'],sc:'Schedule-H',th:'Corticosteroid',df:'Oral'},
  {g:'Prednisolone',b:['Prelone'],c:'Syrup',s:['15mg/5ml'],sc:'Schedule-H',th:'Corticosteroid',df:'Oral'},
  {g:'Dexamethasone',b:['Decadron','Dexona'],c:'Tablet',s:['0.5mg','4mg'],sc:'Schedule-H',th:'Corticosteroid',df:'Oral'},
  {g:'Dexamethasone',b:['Decadron'],c:'Injection',s:['4mg/ml','8mg/2ml'],sc:'Schedule-H',th:'Corticosteroid',df:'Injectable'},
  {g:'Methylprednisolone',b:['Medrol','Solumedrol'],c:'Tablet',s:['4mg','8mg','16mg'],sc:'Schedule-H',th:'Corticosteroid',df:'Oral'},
  {g:'Hydrocortisone',b:['Cortef','Solu-Cortef'],c:'Injection',s:['100mg','250mg'],sc:'Schedule-H',th:'Corticosteroid',df:'Injectable'},
  // ══════ ANTIFUNGAL SYSTEMIC ══════
  {g:'Fluconazole',b:['Diflucan','Forcan','Flucos'],c:'Capsule',s:['50mg','150mg','200mg'],sc:'Schedule-H',th:'Azole Antifungal',df:'Oral'},
  {g:'Itraconazole',b:['Sporanox','Itral','Candiforce'],c:'Capsule',s:['100mg','200mg'],sc:'Schedule-H',th:'Azole Antifungal',df:'Oral'},
  {g:'Griseofulvin',b:['Grisovin','Grifulvin'],c:'Tablet',s:['250mg','500mg'],sc:'Schedule-H',th:'Antifungal',df:'Oral'},
  {g:'Amphotericin B',b:['Fungizone','Ambisome'],c:'Injection',s:['50mg'],sc:'Schedule-H',th:'Polyene Antifungal',df:'Injectable'},
  // ══════ VITAMINS / SUPPLEMENTS ══════
  {g:'Vitamin D3',b:['Sunny-D','D-Rise','Devit-3','Calcirol','D3-Max'],c:'Tablet',s:['1000IU','2000IU','5000IU','60000IU'],sc:'OTC',th:'Vitamin D',df:'Oral'},
  {g:'Vitamin D3',b:['Devit-3','D-Rise'],c:'Drops',s:['400IU/drop','600IU/drop'],sc:'OTC',th:'Vitamin D',df:'Oral'},
  {g:'Vitamin D3',b:['D3-Max'],c:'Sachet',s:['60000IU'],sc:'OTC',th:'Vitamin D',df:'Oral'},
  {g:'Calcium+Vitamin D',b:['Caltrate','Oscal-D','Calcimax-D','Sandocal','Shelcal'],c:'Tablet',s:['500mg+250IU','600mg+400IU','1000mg+800IU'],sc:'OTC',th:'Ca+D Supplement',df:'Oral'},
  {g:'Iron+Folic Acid',b:['Fefol','Iberet','Folvit-Z','Livogen','Orofer'],c:'Tablet',s:['100mg+0.5mg','150mg+0.5mg'],sc:'OTC',th:'Iron Supplement',df:'Oral'},
  {g:'Iron+Folic Acid',b:['Fefol','Orofer'],c:'Syrup',s:['150mg/15ml'],sc:'OTC',th:'Iron Supplement',df:'Oral'},
  {g:'Iron Sucrose',b:['Venofer','Orofer-S'],c:'Injection',s:['100mg/5ml'],sc:'Schedule-H',th:'IV Iron',df:'Injectable'},
  {g:'Multivitamin',b:['Centrum','Pharmaton','Berocca','Theragran','Supradyn','One-A-Day'],c:'Tablet',s:['Multi'],sc:'OTC',th:'Multivitamin',df:'Oral'},
  {g:'Multivitamin',b:['Vidaylin','Becadexamin'],c:'Syrup',s:['200ml'],sc:'OTC',th:'Multivitamin',df:'Oral'},
  {g:'Zinc',b:['Zincovit','Zinc Sulfate','Zincat'],c:'Tablet',s:['20mg','50mg'],sc:'OTC',th:'Mineral',df:'Oral'},
  {g:'Zinc',b:['Baby Zinc','Zincat'],c:'Syrup',s:['20mg/5ml'],sc:'OTC',th:'Mineral',df:'Oral'},
  {g:'Omega-3 Fish Oil',b:['MaxEPA','Omacor','SevenSeas','Fish Oil'],c:'Capsule',s:['500mg','1000mg'],sc:'OTC',th:'Omega-3',df:'Oral'},
  {g:'Vitamin B12',b:['Methylcobal','Neurobion','Mecobalamin'],c:'Tablet',s:['500mcg','1000mcg','1500mcg'],sc:'OTC',th:'Vitamin B12',df:'Oral'},
  {g:'Vitamin B12',b:['Neurobion','Methylcobal'],c:'Injection',s:['1000mcg/ml','2500mcg/ml'],sc:'OTC',th:'Vitamin B12',df:'Injectable'},
  {g:'Vitamin B Complex',b:['Becosules','Neurobion','Beplex','Becadexamin'],c:'Capsule',s:['Multi'],sc:'OTC',th:'B-Complex',df:'Oral'},
  {g:'Vitamin C',b:['Celin','Limcee','Redoxon'],c:'Tablet',s:['100mg','250mg','500mg','1000mg'],sc:'OTC',th:'Vitamin C',df:'Oral'},
  {g:'Vitamin E',b:['Evion','E-Caps'],c:'Capsule',s:['200mg','400mg'],sc:'OTC',th:'Vitamin E',df:'Oral'},
  {g:'Folic Acid',b:['Folvite','Folic Acid'],c:'Tablet',s:['1mg','5mg'],sc:'OTC',th:'Folate',df:'Oral'},
  {g:'Biotin',b:['Biotin','Hairburst','Natrol'],c:'Tablet',s:['2500mcg','5000mcg','10000mcg'],sc:'OTC',th:'B7',df:'Oral'},
  {g:'Glucosamine+Chondroitin',b:['Artiflex','Jointace','Glucosamine'],c:'Tablet',s:['500mg+400mg'],sc:'OTC',th:'Joint Supplement',df:'Oral'},
  {g:'CoQ10',b:['Ubiquinol','Q10','Quten'],c:'Capsule',s:['100mg','200mg','300mg'],sc:'OTC',th:'Antioxidant',df:'Oral'},
  {g:'Probiotics',b:['Culturelle','Align','VSL3','Econorm','Vizylac'],c:'Capsule',s:['Multi'],sc:'OTC',th:'Probiotic',df:'Oral'},
  {g:'Probiotics',b:['Econorm','Vizylac'],c:'Sachet',s:['Multi'],sc:'OTC',th:'Probiotic',df:'Oral'},
  // ══════ UROLOGY / SEXUAL HEALTH ══════
  {g:'Sildenafil',b:['Viagra','Penegra','Vigora','Kamagra'],c:'Tablet',s:['25mg','50mg','100mg'],sc:'Schedule-H',th:'PDE5 Inhibitor',df:'Oral'},
  {g:'Tadalafil',b:['Cialis','Megalis','Tadacip'],c:'Tablet',s:['5mg','10mg','20mg'],sc:'Schedule-H',th:'PDE5 Inhibitor',df:'Oral'},
  {g:'Tamsulosin',b:['Flomax','Urimax','Contiflo'],c:'Capsule',s:['0.2mg','0.4mg'],sc:'Schedule-H',th:'Alpha Blocker',df:'Oral'},
  {g:'Finasteride',b:['Proscar','Finpecia','Propecia'],c:'Tablet',s:['1mg','5mg'],sc:'Schedule-H',th:'5-ARI',df:'Oral'},
  {g:'Dutasteride',b:['Avodart','Dutas'],c:'Capsule',s:['0.5mg'],sc:'Schedule-H',th:'5-ARI',df:'Oral'},
  // ══════ HORMONAL / CONTRACEPTIVES ══════
  {g:'Levonorgestrel+Ethinylestradiol',b:['Microgynon','Yasmin','Marvelon','Diane-35'],c:'Tablet',s:['0.15/0.03mg'],sc:'Schedule-H',th:'Oral Contraceptive',df:'Oral'},
  {g:'Medroxyprogesterone',b:['Provera','Depo-Provera'],c:'Tablet',s:['2.5mg','5mg','10mg'],sc:'Schedule-H',th:'Progestogen',df:'Oral'},
  {g:'Medroxyprogesterone',b:['Depo-Provera'],c:'Injection',s:['150mg/ml'],sc:'Schedule-H',th:'Injectable Contraceptive',df:'Injectable'},
  {g:'Conjugated Estrogens',b:['Premarin'],c:'Tablet',s:['0.3mg','0.625mg','1.25mg'],sc:'Schedule-H',th:'HRT',df:'Oral'},
  {g:'Emergency Contraceptive',b:['Plan B','Postinor-2','iPill'],c:'Tablet',s:['1.5mg'],sc:'Schedule-H',th:'Emergency Contraceptive',df:'Oral'},
  // ══════ MISCELLANEOUS ══════
  {g:'Methotrexate',b:['Trexall','Folitrax'],c:'Tablet',s:['2.5mg','5mg','10mg','15mg'],sc:'Schedule-H',th:'DMARD/Antimetabolite',df:'Oral'},
  {g:'Hydroxychloroquine',b:['Plaquenil','HCQS'],c:'Tablet',s:['200mg','400mg'],sc:'Schedule-H',th:'DMARD',df:'Oral'},
  {g:'Colchicine',b:['Colcrys','Goutnil'],c:'Tablet',s:['0.5mg','0.6mg'],sc:'Schedule-H',th:'Anti-gout',df:'Oral'},
  {g:'Allopurinol',b:['Zyloric','Zyloprim'],c:'Tablet',s:['100mg','300mg'],sc:'Schedule-H',th:'Xanthine Oxidase Inhibitor',df:'Oral'},
  {g:'Adrenaline',b:['Adrenaline','Epinephrine','EpiPen'],c:'Injection',s:['1mg/ml'],sc:'Schedule-H',th:'Emergency',df:'Injectable'},
  {g:'Atropine',b:['Atropine'],c:'Injection',s:['0.6mg/ml','1mg/ml'],sc:'Schedule-H',th:'Anticholinergic',df:'Injectable'},
  {g:'Atropine',b:['Atropine'],c:'Drops',s:['0.5%','1%'],sc:'Schedule-H',th:'Mydriatic',df:'Ophthalmic'},
  {g:'Dopamine',b:['Dopamine','Intropin'],c:'Injection',s:['40mg/ml','200mg/5ml'],sc:'Schedule-H',th:'Vasopressor',df:'Injectable'},
  {g:'Dobutamine',b:['Dobutrex'],c:'Injection',s:['250mg/20ml'],sc:'Schedule-H',th:'Inotrope',df:'Injectable'},
  {g:'Normal Saline',b:['NS','Saline 0.9%'],c:'Injection',s:['100ml','250ml','500ml','1000ml'],sc:'OTC',th:'IV Fluid',df:'Injectable'},
  {g:'Dextrose',b:['D5W','Dextrose 5%','D10W'],c:'Injection',s:['500ml','1000ml'],sc:'OTC',th:'IV Fluid',df:'Injectable'},
  {g:'Ringer Lactate',b:['RL','Hartmann'],c:'Injection',s:['500ml','1000ml'],sc:'OTC',th:'IV Fluid',df:'Injectable'},
  // ══════ BABY CARE ══════
  {g:'Gripe Water',b:['Woodwards','Bonnisan','Colicaid'],c:'Syrup',s:['130ml','200ml'],sc:'OTC',th:'Digestive',df:'Oral'},
  {g:'Simethicone Drops',b:['Infacol','Colicaid','Gas Drops','Mylicon'],c:'Drops',s:['40mg/ml'],sc:'OTC',th:'Anti-flatulent',df:'Oral'},
  {g:'Vitamin D Baby',b:['D-Drops Baby','Aquadeks'],c:'Drops',s:['400IU/drop'],sc:'OTC',th:'Vitamin D',df:'Oral'},
  {g:'Saline Nasal Baby',b:['Little Noses','Nasoclear Baby'],c:'Drops',s:['0.65%'],sc:'OTC',th:'Nasal Saline',df:'Nasal'},
  {g:'Zinc Baby',b:['Baby Zinc','Zedex'],c:'Syrup',s:['20mg/5ml'],sc:'OTC',th:'Mineral',df:'Oral'},
  {g:'Domperidone Baby',b:['Motilium Paed'],c:'Syrup',s:['5mg/5ml'],sc:'Schedule-H',th:'Prokinetic',df:'Oral'},
  // ══════ SURGICAL / FIRST AID ══════
  {g:'Povidone Iodine',b:['Betadine','Pyodine','Wokadine'],c:'Solution',s:['5%','10%'],sc:'OTC',th:'Antiseptic',df:'Topical'},
  {g:'Hydrogen Peroxide',b:['H2O2'],c:'Solution',s:['3%','6%'],sc:'OTC',th:'Antiseptic',df:'Topical'},
  {g:'Chlorhexidine',b:['Savlon','Hexidine'],c:'Solution',s:['0.05%','0.2%','4%'],sc:'OTC',th:'Antiseptic',df:'Topical'},
  {g:'Lignocaine',b:['Xylocaine','Lidocaine'],c:'Injection',s:['1%','2%'],sc:'Schedule-H',th:'Local Anesthetic',df:'Injectable'},
  {g:'Lignocaine',b:['Xylocaine'],c:'Gel',s:['2%'],sc:'OTC',th:'Local Anesthetic',df:'Topical'},
  {g:'Lignocaine',b:['Xylocaine'],c:'Spray',s:['10%'],sc:'Schedule-H',th:'Local Anesthetic',df:'Topical'},
];

module.exports = worldMedicines;
